import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#ff8b9a',
        'primary-fixed-dim': '#d2d0ff',
        'tertiary-fixed-dim': '#c4cbe9',
        'error-dim': '#4f0116',
        'secondary-container': '#d3e4fe',
        'on-tertiary-fixed-variant': '#4e556f',
        'surface-variant': '#d9e4ea',
        'secondary-fixed-dim': '#c5d6f0',
        'inverse-primary': '#8582ff',
        'surface-tint': '#4d44e3',
        'on-primary-container': '#3f33d6',
        'on-error': '#fff7f7',
        'on-secondary-container': '#435368',
        'surface-container': '#e8eff3',
        'on-background': '#2a3439',
        'surface-bright': '#f7f9fb',
        'primary-fixed': '#e2dfff',
        background: '#f7f9fb',
        'surface-dim': '#cfdce3',
        outline: '#717c82',
        primary: '#4d44e3',
        'inverse-surface': '#0b0f10',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#e2dfff',
        'primary-dim': '#4034d7',
        'on-surface': '#2a3439',
        'on-primary-fixed-variant': '#4a40e0',
        'surface-container-high': '#e1e9ee',
        'on-secondary': '#f7f9ff',
        'on-tertiary': '#faf8ff',
        'surface-container-low': '#f0f4f7',
        secondary: '#506076',
        'on-secondary-fixed': '#314055',
        'tertiary-fixed': '#d2d9f8',
        'secondary-fixed': '#d3e4fe',
        'inverse-on-surface': '#9a9d9f',
        'outline-variant': '#a9b4b9',
        'on-tertiary-container': '#444c65',
        'on-surface-variant': '#566166',
        'on-tertiary-fixed': '#323951',
        tertiary: '#575e78',
        'on-primary': '#faf6ff',
        'secondary-dim': '#44546a',
        'on-error-container': '#782232',
        surface: '#f7f9fb',
        'tertiary-dim': '#4b526c',
        error: '#9e3f4e',
        'surface-container-highest': '#d9e4ea',
        'on-secondary-fixed-variant': '#4d5d73',
        'on-primary-fixed': '#2a13c5',
        'tertiary-container': '#d2d9f8',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};

export default config;
