-- Add new role values
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BANK_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BANK_OPS';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BANK_APPROVER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BANK_BRANCH_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BANK_BRANCH_OPERATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MERCHANT_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MERCHANT_USER';

-- Bank branches
CREATE TABLE IF NOT EXISTS "BankBranch" (
  "id" TEXT NOT NULL,
  "bankId" TEXT NOT NULL,
  "nombre" TEXT NOT NULL,
  "codigo" TEXT,
  "localidad" TEXT,
  "region" TEXT,
  "tipo" TEXT,
  "activo" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "BankBranch_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "BankBranch_bankId_idx" ON "BankBranch"("bankId");

ALTER TABLE "BankBranch" ADD CONSTRAINT "BankBranch_bankId_fkey"
  FOREIGN KEY ("bankId") REFERENCES "Bank"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- User relation to bank branch
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bankBranchId" TEXT;
CREATE INDEX IF NOT EXISTS "User_bankBranchId_idx" ON "User"("bankBranchId");
ALTER TABLE "User" ADD CONSTRAINT "User_bankBranchId_fkey"
  FOREIGN KEY ("bankBranchId") REFERENCES "BankBranch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
